### ISSUE TITLE
[Question] Can a username reset its password, without previous password being used?

### ISSUE THREAD

**Issue by DaniellMesquita** [dtube/avalon#12]
For example, I create a account for a Twitch streammer. He joins DTube but shoudn't trust me having its privatekey. Can he change privatekey without the initial privatekey I have working?

**Comment by skzap** [comment]
You don't need to have his private key to create the account for him. He should generate a key-pair on his device, transmit only the public key to you, then you create the account with this public key as an argument.

Of course this will only work when the `NEW_ACCOUNT` transaction is allowed to all accounts (01/08), at the moment it is reserved to the @dtube account.

**Comment by DaniellMesquita** [comment]
But can users reset their password?

**Comment by skzap** [comment]
Yes with the `CHANGE_PASSWORD` transaction they can basically edit the public key for their account. It's not available in the UI yet but will work with CLI.
