### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by DaniellMesquita** [dtube/avalon#13]
As Avalon will have other social networks alongside DTube, what about one sidechain for each, while Avalon is the core?

**Comment by skzap** [comment]
Avalon is the name of the chain engine (akin to Tendermint or Graphene), we aren't going to heavily promote it in terms of marketing for DTube, we're just calling it 'DTube chain' on our side. However it was not designed with video in mind and should work for any type of content. Anyone is open-source and in theory any can use it to build his own chain with social distribution in mind.

We built avalon to be a '1 chain <-> 1 app' concept, not a *cosmos* of chains where all sidechains are technically slaves of the master token. As you can see, Avalon doesn't include any way to put custom transactions (akin to `custom_json` on steem), and doesn't have support for more than 1 tradable asset.

Interconnecting two avalon blockchains must be quite easy tho, as both would have virtually 0 transaction fees and reach finality in only 1 block.

**Comment by DaniellMesquita** [comment]
Thanks for your useful comment. Translating for dumb:
- Avalon is dedicated to DTube, as LBRY blockchain is dedicated to LBRY
- It prevents SPAM, as only accepting transactions of DTube
- Avalon can be forked for a new social network, and a main chain could be created to connect them, with atomic swaps
