### ISSUE TITLE
Check for validity of announced IP of Avalon node leader

### ISSUE THREAD

**Issue by kekkyojin** [dtube/avalon#18]
DTube Avalon uses leaders which are the equivalent to Steem witnesses. They are listed on their own section. Those leaders should add their own IP -or hostname- so other nodes are able to connect to them. When hover the mouse over a leader which has provided a URL, the UI shows it.

It is currently not checking for the IP address to be a valid one. Web page will show that leader as enabled -not grayed- but nodes will be unable to connect to it.

**Comment by skzap** [comment]
Please recreate it on the UI's repo https://github.com/dtube/dtube

The blockchain accepts arbitrary input for the account profile and I do not wish to alter this. I'd rather check for those shenanigans on the UI.

**Comment by kekkyojin** [comment]
Done -> https://github.com/dtube/dtube/issues/110
