### ISSUE TITLE
Avalon doesn't detect it's on old nodejs (v4) and starts

### ISSUE THREAD

**Issue by idikuci** [dtube/avalon#21]
I've tried to start and restart this several times, but it's not able to get past this block. 

```
01:54:19.806 [ERROR] Wrong dist amount 12 11
01:54:19.807 [ERROR] Error Replay { _id: 29774,
  phash:
   '6a69d2d518becedbe448596bdbe7e3a084a0c025ce113d01f507b370b0014518',
  timestamp: 1561493332897,
  txs:
   [ { type: 5,
       data: [Object],
       sender: 'ignacioarreses',
       ts: 1561493330334,
       hash:
        '390d1a85f30e63a56d2464d8356d91efd7cee3c749603e0e23f0cf9484e9da9d',
       signature:
        '2886AuCRihgDT1k1ThfbLUEoMpGCjLkC2EQErzYoTPfF8CmwZRXKgn4WJS7UqyBNWz6Dm2Hr7h2ZN9RJRMshTQJM' } ],
  miner: 'wehmoen',
  dist: 12,
  hash:
   '05c9b84cf4d523a4e761d9851f0d1444e5f9f2aabf8496ef738327fbc834f130',
  signature:
   '5cQFFWqaLu5JmxuNkMUBmMBNxZh8HuMXXgHKcvX4THQJXHaNk7kasHqt7ufuYBQknfnA1Ljh4gAiRu95bRzCoctm' }```

I put a message on a post too but this is probably a better spot for it.

**Comment by skzap** [comment]
I'd be interested to know the versions of nodejs and mongodb used for this. I know this (+-1 dist error) can happen on different nodejs versions but usually avalon should force you to use v10. So maybe its a certain v10 subversion which does it? Or maybe it's the mongodb which is super old and not behaving the same, in which case I guess I should add constraints for the mongodb version too.

**Comment by skzap** [comment]
Talked on discord, apparently this happened under node v4! (a very outdated version still available in apt-get)

Avalon doesn't detect it's on the wrong nodejs version when it's THAT old, so it means we need to improve nodejs version detection on avalon startup.

**Comment by techcoderx** [comment]
closing this as Avalon would crash due to syntax used that is unsupported on old NodeJS versions
