### ISSUE TITLE
Error: invalid signature

### ISSUE THREAD

**Issue by the-blogger** [dtube/avalon#33]
Hello guys. I am getting an error declaring myself as a node leader using the below line:

node src/cli.js profile -K <key> -M <user> '{"node":{"ws":"ws://yourip:yourport"}}'

This is the line that I am executing along with the error that I am getting:

![image](https://user-images.githubusercontent.com/59239265/71452800-372acd00-2745-11ea-9134-142e8bf487f6.png)

I just did this today, 12/25/2019!

I am using the same pub/private keys that I used to log into d.tube in the start.sh file.

**Comment by jvelazqu22** [comment]
I got the same error. Have the same private key in the start.sh file, same pk that I can log into d.tube, and same pk used when running the below command:

node src/cli.js profile -K -M '{"node":{"ws":"ws://yourip:yourport"}}'

It seems like there is a configuration missing or there is a bug in the /transact (post) api

**Comment by be-goood** [comment]
I ran into the same error. I don't know unix and/or nodejs well enough to troubleshoot the /transact api which seems is what is returning the error per the image below:

![image](https://user-images.githubusercontent.com/59315958/71546698-a592a980-2956-11ea-8d6e-1352bdd41c1d.png)

**Comment by techcoderx** [comment]
All of you are able to use the same private key to login to d.tube and transact?

**Comment by techcoderx** [comment]
I think I know what's happening over there. From my output of `curl http://localhost:3001/peers | jq`, looks like you are not fully replayed and receiving blocks.

Please restore the chain state from a backup and try again:

```
mongo
use avalon
db.dropDatabase()
exit

wget https://backup.d.tube/$(date -u +%H).tar.gz
tar -xvf $(date -u +%H).tar.gz
mongorestore -d avalon .
```
