### ISSUE TITLE
Genesis.zip requires at least 4Gig

### ISSUE THREAD

**Issue by skzap** [dtube/avalon#46]
![https://media.discordapp.net/attachments/593091664260759602/761212960181452800/unknown.png](https://media.discordapp.net/attachments/593091664260759602/761212960181452800/unknown.png)

This happens on a 2 gig node. Works fine on a 4gig node.

Its still weird because the genesis.zip file is only 65MB.

**Comment by techcoderx** [comment]
fixed in #52
