### ISSUE TITLE
New accounts starting with ressources

### ISSUE THREAD

**Issue by skzap** [dtube/avalon#55]
Currently, the chain account creation is pretty simple. The user burns some coins, the account gets created with 0 ressources. The user needs to transfer some DTC and wait for ressources to grow.

I think we should somehow take a % of the burn, convert it to VP (maybe a % of the vtPerBurn config) and Bandwidth (not sure how to calculate it), and put it inside the new account created.

Just a random idea and requires some discussions

**Comment by brishtiteveja** [comment]
Sounds like a really good idea.

**Comment by brishtiteveja** [comment]
We should only let this growth for verified account rather than every new account. We need to first have a on chain verification boolean per account.

**Comment by techcoderx** [comment]
As discussed, being verified or not, should not be the factor of whether an account (especially if a burn fee is paid) can perform basic account operations, such as subscribing to some channels so that they show up on the sub feed.
