### ISSUE TITLE
Unclaimed airdrops burn percentage

### ISSUE THREAD

**Issue by skzap** [dtube/avalon#57]
It's only been 2 months out of 6, but so far, only about 30% of the airdrop amounts have been claimed in these two airdrop periods.

I keep an history of what has been distributed and no distributed every month in the dtube/signup repo:

https://github.com/dtube/signup/tree/master/airdrop_history

The last distribution month will be March 2021, so we need to decide what to do with the final unclaimed airdrops which will coincidentally happen on April 1st 2021. At the current rate, it should represent about 1.4M DTC, a hefty sum.

I propose that we first settle on the % amount that we will burn. If you have ideas about what to do with the coins we will not burn, please keep it on the discord channel, or create a new issue in this repo. First we should settle on the burn amount, then we will discuss about what we do with the remainings tokens.

**Comment by tibfox** [comment]
since it will be about 1.4M DTC I am for burning minimum 50% and keep the rest for other purposes!

**Comment by skzap** [comment]
I think 80% burn would be my 'honest' number. It would leave us with plenty of space to use the remaining funds without any potential of destroying the economy. And we definately forgot to dedicate some funds to certain things (like dtube.signup and uniswap) before launching the chain.

**Comment by steeminator3000** [comment]
I think the time of the burn is quite significant topic but if we are going to decide the percentage I would go with 75 percent, I personally think keeping some of the unclaimed token and being completely transparent on where those funds will be used is the best option.

**Comment by prcolaco** [comment]
With a burn of 75%, that means that the reserved fund would be ~350K DTC, at prices of today ~$87,500. That is a fair amount for driving adoption and others like liquidity pool on uniswap. Also the reduced supply might bring price up a bit. Based on these I also agree with the 75% burn.

**Comment by brishtiteveja** [comment]
I second tibfox with 50%, then use the rest for dev, marketing etc. in a very transparent manner.

**Comment by skzap** [comment]
@steeminator3000 why do you think the time of the burn is important? Because of the VP it currently generates?

**Comment by Birdinc** [comment]
80% sounds fair, a 100% burn would be even better; as scarcity drives value.  

With any burn, value immediately transfers to every network participant equally based on the stake they hold, even though it may not seem or  feel like it.

**Comment by techcoderx** [comment]
I would say burn 100% if possible

**Comment by steeminator3000** [comment]
@skzap  I think a big burn like that will only hurt the marketcap at this point so I think timing is an important aspect in this burn event aswell.

**Comment by techcoderx** [comment]
Agreed, there will be a huge supply shock when burning such a large amount at one time. Probably could use it to offset inflation over time through periodic burn

**Comment by hightouch67** [comment]
I don't really understand the impact on the marketcap because it seems to be defined by the erc20 token. So nothing would change, literally.

Otherwise I agree with a 75% burn and maybe starting it soon. It will leave enough funds for the team to do different stuff like creating accounts, attracting users, creating bounties for dev/issues, empowering creators, etc...

Burning 100% is not a good idea in my opinion even if I understand your will. It's always better for a project of this size to keep some funding. And by burning 100% you can't go back, but with 75% you can still burn the 25% later if needed.

**Comment by nannal** [comment]
I agree with steeminator and techcoder and think that that a single large burn would have an impact on the pool and should be avoided in favour of a slow & regular burn or transfer of coins to an account who's priv key is unknown to all. 

I would further argue that a much larger sum than 75% should be burned, even with a burn of 90% 140k DTC would still be held, which at current holdings would make airdrop the fourth largest holder (behind dtube, swap and mar1..) this will obviously change to some degree due team share and future claims but the point stands it would be a very powerful account.

Before being able to make any clear decision I would oppositely argue that the exact requirements need to be laid out, account creation & exchange pool liquidity were listed as two possible uses for the unclaimed coins, but these both raise further questions, pool liquidity requires an equal value sum of another token be provided, who would provide that token & furthermore who would benefit from any gains accumulated? Currently DTube makes accounts for free, has it's own DTC holdings and only transfers VP & BW, while also claiming 10% of inflation, so is there a requirement for airdropped tokens to be utilised for this? 

I hope it's clear that **we're being asked to set a price without knowledge of what we're buying.**

**Comment by prcolaco** [comment]
I have to also agree that @nannal has a point here...

First we need to decide if there's a major burn, which I think that we all are in favour, at least didn't get anyone opposing it.

Then we should first identify all the destinations of the reserve pool, so that we can agree to an exact number for said pool.

**Comment by skzap** [comment]
I agree has has a point, it's a bit hard to ask you to decide on how much we should burn if we don't know what we're going to do with it.

Leaders should be in control of what we don't burn. We can keep using git to talk about it, or we could setup some off-chain proposal/voting thingy using avalon keys and each leader node approval as power. And if we realize we didn't burn enough, then we will burn more :smiling_imp:. We should do it rather quick, because as long as these funds exist, it keeps dtube in a dictatorship mode where I can virtually control 1/3+ of the leaders slots if I start voting strategically with these funds.

I'd rather not do a new account, and have the funds stay in the @dtube account (could be programatically locked though), purely because of the VP generation that we can give in a positive way via partnership program / signup faucet. Or else we need to extend the transfer vp feature to more accounts.

I'm happy to see everyone agreeing on big-ish numbers. From discussions it seems 75% is currently the median amount.

I also agree that we should do it gradually, there is no purpose in suddently creating a supply shock on the dtube economy. Ideally it could be done on the 1st day of each month. i.e. on jan 01 2021 we burn 75% of the unclaimed airdrops from october 2020, which could offset some of the sell pressure we see from crackheads when a new airdrop period opens.

@nannal : 10% of the expected yearly inflation is only 80,000 DTC. These funds won't get touched, as long as the funds from past income (steem), and fundraiser (100K$ worth of crypto when bitcoin was between 5K and 12K) are available. So expect dtube to hold dtcs for a long, long time, unless I start going crazy with the spendings.

**Comment by Lintendlor** [comment]
It would be best to burn at a rate of 75 to 90. I mentioned before on discord. The announcement of this has already been made, and the 1.4M is really huge amount, we can burn 75% of it and use it for the benefit.

**Comment by dbigge** [comment]
Could use part or most of it to create liquidity pool on Uniswap.  Could create a no admin key pool.  This would ensure DTC is left in the liquidity pool...if the price drops low that DTC will always remain for buyers.  If the price goes High ETH would be locked for liquidity.  Both are good for DTUBE.  Auction off some this unclaimed DTC via another ICO round to raise ETH.  ETH and DTC remaining go into a smart contract that when executed adds liquidity to Uniswap...with no admin keys.

**Comment by nannal** [comment]
@dbigge 

> account creation & exchange pool liquidity were listed as two possible uses for the unclaimed coins, but these both raise further questions, pool liquidity requires an equal value sum of another token be provided, who would provide that token & furthermore who would benefit from any gains accumulated?

**Comment by techcoderx** [comment]
Closing this as DTUBEs are being successfully burned periodically
