### ISSUE TITLE
Sorting options for /blog endpoint

### ISSUE THREAD

**Issue by MENOZE** [dtube/avalon#66]
Is there a way to change the order of the videos on the channel page when viewing it publicly? I notice that the videos are posted in the order of the posted date. I have videos that are from YouTube that are older than my newest videos, but are in front.

**Comment by skzap** [comment]
Avalon isn't really designed to achieve this. Better using the ElasticSearch for it instead, it will be much more efficient.

**Comment by skzap** [comment]
If attempted, it would require too many indexes on the collections to have respectable speed at scale.

**Comment by brishtiteveja** [comment]
@skzap well, we can use the power of mongodb "find" function. Working on a solution... we will see.
