### ISSUE TITLE
Buyback policy for DTC

### ISSUE THREAD

**Issue by danimesq** [dtube/avalon#67]

**Comment by techcoderx** [comment]
Low priority at this stage due to #57

**Comment by DaniellMesquita** [comment]
Reference and inspiration:

https://gov.yearn.finance/t/yip-56-buyback-and-build/8929
https://cryptobriefing.com/yearn-buyback-and-build-boosts-yfi-token-price-launch/

**Comment by techcoderx** [comment]
heim made the buyback contract after HF6 activation, details [here](https://d.tube/#!/v/heimindanger/c4wf5v8p47u), contract may be viewed [here](https://bscscan.com/address/0x619126cd55992c11395ed0520e38e68a66e23753).
