### ISSUE TITLE
Program halt

### ISSUE THREAD

**Issue by DevDeckardCain** [dtube/avalon#86]
Had an issue with my internet dropping out (regular occurrence for the time being. ISP infrastructure is to blame), which caused this problem:

15:23:49.285 [ERROR] unauthorized miner
15:23:49.285 [WARN] miner worker trying to mine but couldnt Block {
  _id: 9000757,
  phash: '227c4ca3f8ceb13be6f39efd29b4aca86dd72280e625d6721d03586707236ff0',
  timestamp: 1629919429284,
  txs: [],
  miner: 'devdeckardcain94',
  hash: undefined,
  signature: undefined
}

Once that error comes up, the program halts. It's still running, just not doing anything.

**Comment by techcoderx** [comment]
`unauthorized miner` means that the miner of the current block is not scheduled to produced the very next block or have not produced the last 15 blocks (in case the next scheduled miner is missing). Could be due to a bad peer in this case
