### ISSUE TITLE
Avalon IPFS Pinning Script

### ISSUE THREAD

**Issue by DevDeckardCain** [dtube/avalon#88]
https://ipfs.io/ipfs/QmfSgV1dVQ7PoQDyw1vePNCeUbBsKHYxoJtc636s1Y1fWM?filename=pinFollowing.sh

This script pins all videos from either: a list of people an account follows, or videos from a specific user

Example:
./pinFollowing.sh 240 true false devdeckardcain94

Where 240 is the quality I desire to pin (240, 480, 720, 1080), the second parameter determines whether I wish to pin (true) or just output the CID's (false), the third parameter is to determine what we should do with the fourth (true == load the following list from the user, false == just load the list of videos from this single user) and finally parameter four which is the account you're targeting. 

Video tut: https://d.tube/v/devdeckardcain94/QmWcX9utpvJmp3Qa7fa1dFoxuk9k5c8jbjnjwM26zKstKh

**Comment by techcoderx** [comment]
Closing this as pin script link seems to be dead, reopen when it is accessible again
